apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nexus-host
spec:
  rules:
    - host: "artifactory.esl.corp.elbit.co.il"
      http:
        paths:
          - pathType: Prefix
            path: "/global_operations--docker"
            backend:
              service:
                name: nexus
                port:
                  number: 8080
