apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-data
  labels:  
   type: local
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/shacharovadia/Desktop/Projects//nexus/k8s/"
